rm(list = ls())
require(latex2exp)
# LOADING THE FILE GENERATED BY simulation_estimation.R
load("simulations_data/simulations_estimation_V2.Rdata")

# NAMES OF DIFFERENT BOXPLOTS
############################################################################
mains <- vector("expression", 6)
mains[1] <- TeX("Estimation of $\\Gamma_{11} = 0$")
mains[2] <- TeX("Estimation of $\\Gamma_{12} = -1.5$")
mains[3] <- TeX("Estimation of $\\Gamma_{13} = \\sqrt{3}/2$")
mains[4] <- TeX("Estimation of $\\Gamma_{21} = 0$")
mains[5] <- TeX("Estimation of $\\Gamma_{22} = 1$")
mains[6] <- TeX("Estimation of $\\Gamma_{23} = \\sqrt{3}$")
###############################################################################

# LIMITS OF THE DIFFERENT BOXPLOTS
############################################################################
MAX <- MIN <- matrix(nrow = 6, ncol = 2)
colnames(MAX) <- colnames(MIN) <- c("setI", "setII")
for (s in c("setI", "setII")) {
  for (i in 1:6) {
    for (cont in p_conts) {
      MAX[i, s] <- max(MAX[i, s], 
                       est[["ML"   ]][[s]][[as.character(cont)]][, i],
                       est[["MDPD" ]][[s]][[as.character(cont)]][, i], 
                       est[["OBR"  ]][[s]][[as.character(cont)]][, i], 
                       est[["wRGLM"]][[s]][[as.character(cont)]][, i],
                   na.rm = T)
      MIN[i, s] <- min(MIN[i, s], 
                       est[["ML"   ]][[s]][[as.character(cont)]][, i],
                       est[["MDPD" ]][[s]][[as.character(cont)]][, i], 
                       est[["OBR"  ]][[s]][[as.character(cont)]][, i], 
                       est[["wRGLM"]][[s]][[as.character(cont)]][, i],
                       na.rm = T)
    }
  }
}
mains1 <- estimators
mains1[3] <- "RGLM"
###############################################################################

# CREATING 2 * 6 GRAPHS OF BOXPLOTS OF ESTIMATES UNDER SETTING I AND II
############################################################################
# for each setting, 6 boxplots are generated
for (set in c("setI", "setII")) {
  # for each of the 6 gamma coordinates, a boxplot is generated
  for (i in 1:6) {
    # name of the image
    file_name <- paste("figures/boxplots/boxplot_", set, "_", i, ".pdf", 
                       sep = "")
    
    # graphical parameters
    pdf(file = file_name, width = 5.5, height = 5, pointsize = 8)
    par(family = "mono", mar = c(4, 4, 5, 1.7) + 0.1, 
        cex.axis = 1.1, cex.lab = 1.1)
    layout(matrix(1:4, byrow = T, nrow = 2))
    
    # for the 4 estimators, plot estimates of i-th coordinate of gamma
    for (j in 1:4) {
      # estimates of the j-th estimators of the i-th componenet of gamma
      est_tmp <- matrix(nrow = M, ncol = length(p_conts))
      colnames(est_tmp) <- as.character(p_conts)
      for (p_c in as.character(p_conts)) {
        est_tmp[, p_c] <- est[[estimators[j]]][[set]][[p_c]][, i]
      }
      
      # plot boxplot
      boxplot(est_tmp, at = 100 * p_conts, 
              xlim = c(0 - 0.2, 5 + 0.2), ylim = c(MIN[i, set],  MAX[i, set]), 
              main = "", ylab = "Estimate", xlab = paste("Contamination (%)
", mains1[j]), pch = 19, names = 100 * p_conts, boxwex = 0.7)
      
      # abline at true parameter value
      abline(h = c(t(gamma))[i])
    }
    
    # add general title to the plot
    mtext(outer = T, line = -2, text = mains[[i]], cex = 1.1)
    if (s == "setI") {
      mtext(outer = T, line = -3.5, text = "Setting I", cex = 1.1)
    } else {
      mtext(outer = T, line = -3.5, text = "Setting II", cex = 1.1)
    }
    dev.off()
  }
}
###############################################################################