# THIS SCRIPT USES THE RData FILE GENERATED BY THE SCRIPT "cross_validation.R"

cpt <- 2

path_in <- c("ten_fold_likelihoods_mammo.RData",
           "ten_fold_likelihoods_vert.RData")
load(path_in[cpt])

mains <- c("Mammography", "Vertebral column")

# SETTING GRAPHICAL PARAMETERS
###############################################################################
est <- c("ML", "MDPD", "RGLM", "OBR")

path_out <- c("figures/application_boxplots_mammo.pdf",
             "figures/application_boxplots_vert.pdf")
# pdf(file = path_out[cpt],
#     width = 6, height = 6, pointsize = 9)
pdf(file = path_out[cpt], width = 6, height = 4, pointsize = 9)

par(family = "mono", mar = c(4, 4, 5, 1.7) + 0.1, 
    cex.axis = 1.1, cex.lab = 1.1)
layout(matrix(1, byrow = T, nrow = 2))
###############################################################################

# MAKING BOXPLOTS
###############################################################################
Vert <- likelihoods_XV[[1]] 
boxplot(Vert[, order(apply(abs(Vert), 2, median, na.rm = T))], 
        main = mains[cpt],
        names = est[order(apply(abs(Vert), 2, median, na.rm = T))],
        las = 2, pch = 19, 
        ylab = "Median individual likelihood",
        xlab = "Estimators", 
        col = "white",
        boxwex = 0.5)



dev.off()
